In [8]:
import os
import pandas as pd
import sys

sys.path.append(os.path.abspath(os.path.join(os.path.dirname('__file__'), '..')))

In [9]:
px_data = pd.read_csv('../px_data.csv')

In [10]:
px_data.head()

,date,open,high,low,close,adjClose,volume,unadjustedVolume,change,changePercent,vwap,label,changeOverTime,symbol
0,2025-02-14,1044.95,1064.50,1041.69,1058.60,1058.60,3133301,3133301,13.65,1.31000,1052.4350,"February 14, 25",0.013100,NFLX
1,2025-02-13,1026.63,1045.99,1025.10,1043.69,1043.69,3476100,3476100,17.07,1.66000,1035.3525,"February 13, 25",0.016600,NFLX
2,2025-02-12,1005.49,1027.74,998.35,1027.31,1027.31,3389000,3389000,21.82,2.17000,1014.7225,"February 12, 25",0.021700,NFLX
3,2025-02-11,1020.79,1022.69,1002.95,1008.08,1008.08,3331800,3331800,-12.71,-1.25000,1013.6275,"February 11, 25",-0.012500,NFLX
4,2025-02-10,1023.05,1032.85,1015.88,1027.60,1027.60,3296600,3296600,4.55,0.44475,1024.8450,"February 10, 25",0.004448,NFLX

In [11]:
header = px_data.columns

In [ ]:
#%run ./../src/formatter.py

from src.formatter import convert_to_snake_case

In [13]:
px_data.columns =px_data.columns.map(convert_to_snake_case)